#!/bin/bash

export HADOOP_LOG_DIR=/tmp

LOG_FILE=hadoop.log

rm -f $LOG_FILE

hdfs balancer "$@" &
balancer_pid=$!

sleep 15

RET_VAL=0

while ps -p $balancer_pid > /dev/null ; do
  if grep -i error $LOG_FILE > /dev/null ; then
    echo "found Error in $LOG_FILE, killing process $balancer_pid"
    kill -9 $balancer_pid
    RET_VAL=1
  fi
  sleep 15
done

exit $RET_VAL
